*** Settings ***
# Code Generated by Sidekick is for learning and experimentation purposes only.
Library    RequestsLibrary
Resource   ../../../resources/variable.robot
Resource   ../../../resources/keyword.robot

Suite Setup    Load Access Token And Account Data

*** Test Cases ***
Read Account And Validate Data
    [Tags]    smoke    regression
    ${account_id}=    Create Account With Valid Data
    ${headers}=    Create Dictionary    Authorization=Bearer ${ACCESS_TOKEN}
    ${resp}=    GET    ${INSTANCE_URL}/services/data/${API_VERSION}/sobjects/Account/${account_id}    headers=${headers}
    Should Be Equal As Integers    ${resp.status_code}    200
    ${account}=    To Json    ${resp.content}
    Should Be Equal    ${account['Id']}    ${account_id}
    Log To Console   ${resp}
    Log To Console   ${resp.text}
