*** Settings ***
# Code Generated by Sidekick is for learning and experimentation purposes only.
Library    RequestsLibrary
Resource   ../../../resources/variable.robot
Resource   ../../../resources/keyword.robot

Suite Setup    Load Access Token And Account Data

*** Test Cases ***
Create New Account
    [Tags]    smoke    regression
    ${user_id}=    Create Account With Valid Data
    Log To Console    Created Account with ID: ${user_id}
